### ISSUE TITLE
Statamic 4 / Laravel 10 support

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [siterig/statamic-sendinblue#3]
Are there any news regarding Statamic 4 / Laravel 10 support?

**Comment by MeMattStone** [comment]
We've been actively working on updating our Statamic add-ons, we're a bit behind schedule as we had originally hoped to have them ready by October but our main developer has been on paternity leave. Our current ETA for a release is mid-December

**Comment by davydokter** [comment]
Hi @MeMattStone,

We are using this addon for one of our sites. We want to update our site to Statamic 4 & Laravel 10 but this issue is currently blocking that upgrade. Could you let me know when you guys expect to be done with this?

Kind regards,
Davy

**Comment by MeMattStone** [comment]
Hi @davydokter , I'm reviewing the work in the PR mentioned above this week and am aiming to have this completed and released by the end of the week

**Comment by MeMattStone** [comment]
This add-on has now been updated to our latest release adding support for Statamic 4 and Laravel 9 or 10
