### ISSUE TITLE
Could not locate configuration for 'sendinblue'

### ISSUE THREAD

**Issue by qbixx** [siterig/statamic-sendinblue#6]
I’m currently working on an Statamic v4 website and have installed the Brevo module (https://statamic.com/addons/siterig/sendinblue ). I followed the install instructions and installed the module with: `composer require siterig/sendinblue` and published the config.

The module installed automatically the `dev-feature/SRP-11-Update-Sendinblue-for-Statamic-v4` branch.

After setting up the form in Statamic I wanted to connect the form to Brevo. I set everything up on /cp/sendinblue/config/edit. However as soon as I would like to save the settings I get an error:

Could not locate configuration for 'sendinblue'

Is there a way to save the form?

**Comment by MeMattStone** [comment]
Hi, do you have multiple forms setup in Statamic?

**Comment by qbixx** [comment]
Hi @MeMattStone, there is only one form setup in Statamic. The 'newsletter' form is currently the only one that is added to the website.

**Comment by MeMattStone** [comment]
Hi @qbixx , we've just released an update that should fix your issue. I'd recommend removing the configuration files and the add-on and install from scratch. If you can let me know if that fixes your issue, thanks
