### ISSUE TITLE
Statamic v5 / Laravel 11

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [siterig/statamic-sendinblue#9]
Any plans on compatibility with Statamic v5 / Laravel 11?

**Comment by MeMattStone** [comment]
Hi, yes we should be getting the next version out by the end of the month which will add compatibility

**Comment by MeMattStone** [comment]
This release is now published (v2.0.0)

**Comment by SevendaysCompany** [comment]
any plans on compatibility with laravel 12?

**Comment by MeMattStone** [comment]
Yes, we are releasing a new version in the next couple of weeks which will add support for Statamic v6 and Laravel 12

**Comment by MeMattStone** [comment]
> any plans on compatibility with laravel 12?

Latest version (v2.0.2) now supports Laravel 12
